---

- name: Install and enable postgres repository
  dnf:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm' 
    state: present
    disable_gpg_check: yes

- name: Disable default modular stream
  command: dnf -qy module disable postgresql

# some perl dependencies have been moved to the powertools repo (for EL9, it would be the CRB repo) 
- name: install the powertools repository
  command: "dnf config-manager --set-enabled powertools"

- name:  Install postgres packages
  dnf: 
    name: 
      - postgresql15-contrib
      - postgresql15-devel
      - postgresql15-libs
      - postgresql15-server
    state: present

- name: store the statistics of /var/lib/pgsql/15/data/PG_VERSION
  stat:
    path: /var/lib/pgsql/15/data/PG_VERSION
  register: pg_data

- name: Initialize the database
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  when: pg_data.stat.exists == false

- name: Start and enable postgres service
  service: 
    name: postgresql-15
    state: started 
    enabled: yes

- name: Upload pgsql_profile file (to include the correct PATH)
  copy: 
    src: .pgsql_profile
    dest: /var/lib/pgsql/.pgsql_profile
    owner: postgres
    group: postgres
