---

- name: Install and enable postgres repository
  dnf:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm' 
    state: present
    disable_gpg_check: yes

- name: Disable default modular stream
  command: dnf -qy module disable postgresql

- name:  Install postgres packages
  dnf: 
    name: 
      - postgresql11-contrib
      - postgresql11-devel
      - postgresql11-libs
      - postgresql11-server
    state: present

- name: store the statistics of /var/lib/pgsql/11/data/PG_VERSION
  stat:
    path: /var/lib/pgsql/11/data/PG_VERSION
  register: pg_data

- name: Initialize the database
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  when: pg_data.stat.exists == false

- name: Start and enable postgres service
  service: 
    name: postgresql-11 
    state: started 
    enabled: yes
