---

- name: Install redis modularity appstream 
  dnf:
    name: '@redis:6'
    state: present

- name:  Install redis packages
  dnf: 
    name: 
      - redis
    state: present

- name: Start and enable redis service
  service: 
    name: redis 
    state: started 
    enabled: yes
