---

- name: Install snmpd packages
  dnf: 
    name: 
      - net-snmp
      - net-snmp-utils
      - net-snmp-libs
    state: present

- name: "Make sure that the snmpd conf file doesn't contain the new observium username already"
  lineinfile:
    name: /etc/snmp/snmpd.conf
    line: "rouser {{ observium_username }}"
    state: present
  check_mode: yes
  register: observium_user_exists

- name: Stop snmpd service in case it's running
  service: 
    name: snmpd 
    state: stopped
  when: observium_user_exists.changed == true

- name: Create snmp user
  ansible.builtin.command: net-snmp-create-v3-user -ro -a {{ observium_password }} -A SHA -x {{ observium_crypto }} -X AES {{ observium_username }}
  when: observium_user_exists.changed == true

- name: Start and enable snmpd service
  service: 
    name: snmpd 
    state: started 
    enabled: yes

- name: Download observium agent
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/DanielleHuisman/observium-community-edition/main/scripts/observium_agent
    dest: /usr/lib/observium_agent
    mode: '0744'

- name: Upload observium_agent.socket
  copy:
    src: ./files/observium_agent.socket
    dest: /etc/systemd/system/observium_agent.socket

- name: Upload observium_agent@.service
  copy:
    src: ./files/observium_agent@.service
    dest: /etc/systemd/system/observium_agent@.service

- name: Start and enable observium agent socket
  service:
    name: observium_agent.socket
    state: started
    enabled: yes

- name: Directory for observium application scripts
  ansible.builtin.file:
    path: /usr/lib/observium_agent/local
    state: directory

# TODO get distro script

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- include_tasks: nginx.yml
