
- name: Install python3
  dnf:
    name: python3
    state: present
  when: "'nginx' in ansible_facts.packages and ansible_os_family == 'RedHat'"

- name: Select python 3 as the default
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
    state: selected
  when: "'nginx' in ansible_facts.packages and ansible_os_family == 'RedHat'"

- name: Download nginx agent
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/DanielleHuisman/observium-community-edition/main/scripts/agent-local/nginx
    dest: /usr/lib/observium_agent/local/nginx
    mode: '0744'
  when: "'nginx' in ansible_facts.packages"

- name: Patch the agent to query 127.0.0.1 instead of localhost
  ansible.builtin.lineinfile:
    path: /usr/lib/observium_agent/local/nginx
    regexp: '^data = urlopen'
    line: data = urlopen('http://127.0.0.1/nginx-status').read().decode('utf-8')


- name: Upload nginx status conf
  copy:
    src: ./files/stub-status.conf
    dest: /etc/nginx/conf.d/stub-status.conf

- name: Reload service nginx
  service:
    name: nginx
    state: reloaded
