---

- name: Install MariaDB related packages
  dnf: 
    name: ['mariadb-server', 'python3-PyMySQL'] 
    state: present
  
- name: Start and enable mariadb service
  service: 
    name: mariadb 
    state: started 
    enabled: yes

# needs: ansible-galaxy collection install community.mysql
- name: Update mysql root password for all root accounts
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true # check_implicit_admin throws error on second pass (once the password was set) 
    
- name: Remove the MySQL test database
  mysql_db: 
    db: test 
    state: absent 
    login_user: root
    login_password: "{{ mysql_root_password }}"
