---

- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Upgrade all packages
  package:
    name: "*"
    state: latest
  when: ansible_os_family != "RedHat" and ansible_distribution_major_version != "8"

- name: Install yum-utils
  dnf:
    name: yum-utils
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "8"

# workaround for RH family major version 8 where ansible-core 2.18 requirements on python do not match the python3-dnf.noarch package version of python
- name: Upgrade packages on RH-like machines version 8
  command: "dnf -y upgrade"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Check for reboot hint on Centos/RH.
  command: needs-restarting -r
  check_mode: yes
  when: ansible_os_family == "RedHat"
  register: reboot_hint_centos

- name: Check for reboot hint on Debian.
  stat:
    path: /var/run/reboot-required
  check_mode: yes
  when: ansible_os_family == "Debian"
  register: reboot_hint_debian

# - debug: var=reboot_hint_centos.rc
# - debug: var=reboot_hint_debian.stat.exists

- name: Restart server
  reboot:
  when: > 
    (
        (reboot_hint_centos.rc is defined and reboot_hint_centos.rc == 1) 
      or 
        (reboot_hint_debian.stat.exists is defined and reboot_hint_debian.stat.exists == True)
    ) 
    and 
    (
      skip_unnecessary_steps is defined and skip_unnecessary_steps != 1
    )
