---

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: Install remi repo.
  dnf:
    name: "{{ remi_repo_url }}"
    state: present

- name: Install php modularity appstream 
  dnf:
    name: '@php:remi-7.4'
    state: present

- name:  Install php packages
  dnf: 
    name: 'php, php-fpm, php-cli, php-common, php-gd, php-ldap, php-mbstring, php-mcrypt, php-mysql, php-mcrypt, php-pdo, php-pear, php-pecl-apc, php-process, php-xml'
    state: present

- name: Start and enable php-fpm service
  service: 
    name: php-fpm 
    state: started 
    enabled: yes


- name: Restart service httpd so that it pick ups php
  service:
    name: httpd
    state: restarted
