---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Check if REMI repo is already configured.
  stat: path={{ remi_repofile_path }}
  register: remi_repofile_result

- name: Install REMI repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not remi_repofile_result.stat.exists

- name: Import REMi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present
  when: not remi_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  
- name: Upgrade all packages
  package: name=* state=latest update_cache=yes
