---

- name:  Install EPEL repo
  dnf: 
    name:  epel-release 
    state: present

#TODO move Remi repo to the php role
- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: Install remi repo.
  dnf:
    name: "{{ remi_repo_url }}"
    state: present

