---

- name:  Install EPEL repo
  dnf: 
    name:  epel-release 
    state: present

- name: Change EPEL priority
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: priority
    value: '10'
    backup: no

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: Install remi repo.
  dnf:
    name: "{{ remi_repo_url }}"
    state: present

