---

- name: Install php modularity appstream 
  dnf:
    name: '@php:remi-7.4'
    state: present

- name:  Install php packages
  dnf: 
    name: ['php', 'php-cli', 'php-common', 'php-gd', 'php-ldap', 'php-mbstring', 'php-mcrypt', 'php-mysql', 'php-mcrypt', 'php-pdo', 'php-pear', 'php-pecl-apc', 'php-process', 'php-xml']
    state: present